version: "3"

services:
  adguardhome-unbound:
    container_name: adguard-unbound
    hostname: agh-unbound
    image: sb/adguard-unbound
    network_mode: "bridge"
    restart: unless-stopped
    ports:
      # disable this port after first setup
      - 3000:3000/tcp
      # plain DNS
      # - 6553:53/tcp
      # - 6553:53/udp
      # add if you intend to use AdGuard Home as a DHCP server
      # - 67:67/udp
      # - 68:68/tcp
      # - 68:68/udp
      # add if you are going to use AdGuard Home's admin panel as well as run AdGuard Home as an HTTPS/DNS-over-HTTPS server
      # - 8002:80/tcp
      # change this port for security reason to use AdGuard Home's admin panel
      - 5443:5443/tcp
      - 5443:5443/udp
      # add if you are going to run AdGuard Home as a DNS-over-TLS server
      - 853:853/tcp
      # add if you are going to run AdGuard Home as a DNS-over-QUIC server.
      - 853:853/udp
      # add if you are going to enable unbound access on local server
      #- 5035:5035/tcp
      #- 5035:5035/udp
    # Volumes store your data between container upgrades
    volumes:
      # adguardhome container work directory
      - ./work:/opt/adguardhome/work
      # adguardhome container conf directory
      - ./conf/agh:/opt/adguardhome/conf
      # ssl certificates for domain and subdomain, don't forget to change example.com to your domain
      - /home/dns/nginx/dns.example.com:/cert
      # unbound dir with custom config
      - ./conf/unbound:/opt/unbound
      # DNSSEC key and root hints from dns-root-data package
      - /usr/share/dns:/usr/share/dns
    environment:
      - TZ=Europe/Kiev
      - UID=1001
      - GID=1001
